name: courtfinder
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  fire_functions:
    git:
      url: https://github.com/ProPorygon/FireFunctions
      ref: dev
#    path: /Users/kevin/Development/fire_functions
  google_sign_in: "^3.0.2"
  firebase_auth: ^0.5.5
  firebase_core: ^0.2.3
  location: ^1.2.0
  shared_preferences: ^0.4.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - images/court.png
  - images/chicago.jpg
  - images/newyork.jpg
  - images/losangeles.jpg
  - images/ruckerpark.jpg
  - images/basketball_icon.png
  - images/venicebeach.jpg
  - images/lincolnpark.jpg
  - images/manhattan.jpg
  - images/brooklyn.jpg
  - images/bronx.jpg
  - images/queens.jpg
  - images/statenisland.jpg
  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  fonts:
    - family: Helvetica
      fonts:
        - asset: fonts/Helvetica-Regular.ttf
        - asset: fonts/Helvetica-Bold.ttf
